apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstoreapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstoreapp
  template:
    metadata:
      labels:
        app: petstoreapp
    spec:
      containers:
      - name: petstoreapp
        image: petstoreservice.azurecr.io/petstorepetservice:latest
        ports:
        - containerPort: 80
        env:
        - name: PETSTOREPETSERVICE_SERVER_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: petstoreapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: petstoreapp
